version: '3'
services:
  node:
    image: node:16
    container_name: node
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm start
    environment:
      NODE_ENV: production
    ports:
      - 4000:8081
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: your_password
      PMA_DB_NAME: your_database
    ports:
      - 8099:80
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - node
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local