require('dotenv').config()
module.exports={
    HOST:process.env.DB_HOST2,
    USER:process.env.DB_USER,
    PASSWORD:process.env.BD_PASS2,
    DB:process.env.MYSQL_DB,
    dialect:"mysql",
    pool:{
        max:15,
        min:0,
        acquire:30000,
        idle:10000
    }
};